%% SMART TRAFFIC SYSTEM FOR AMBULANCES
% IoT-Based Transmitter and Receiver Simulation
%
% Course       : Control System
% Institution  : National Institute of Technology Nagaland
%
% Team Members :
% 1. Malothu Lokesh
% 2. Guguloth Manusha
% 3. Dondapati Harshavardhini
%
% Guided By    : Dr. Daijiri Narzary
% MATLAB       : R2024b

clc;
clear;
close all;

%% 1. SYSTEM PARAMETERS

% Simulation time
Ts = 0.01;                 % Sampling time
t = 0:Ts:10;               % 10-second simulation

% Communication delay
delay = 0.5;               % IoT communication delay (seconds)
delay_samples = round(delay / Ts);

%% 2. AMBULANCE TRANSMITTER

% Emergency signal generated by ambulance transmitter
Tx_signal = square(2*pi*1*t);

%% 3. WIRELESS COMMUNICATION CHANNEL

% Initialize received signal
Rx_signal = zeros(size(Tx_signal));

% Apply communication delay
Rx_signal(delay_samples+1:end) = ...
    Tx_signal(1:end-delay_samples);

%% 4. RECEIVER SIGNAL FILTERING

% Low-pass filtering to reduce simulated communication noise
Rx_filtered = lowpass(Rx_signal, 0.5, 1/Ts);

%% 5. EMERGENCY ALERT DETECTION

% Activate alert when emergency signal is detected
Cyron_alert = Rx_filtered > 0;

%% 6. DRIVER RESPONSE MODEL

% Proportional control gain
Kp = 2;

% Driver response based on emergency alert
Driver_Response = Kp * double(Cyron_alert);

%% 7. DISPLAY SIMULATION RESULTS

figure('Name', ...
    'Smart Traffic System for Ambulances', ...
    'NumberTitle', 'off');

% Transmitter signal
subplot(4,1,1);

plot(t, Tx_signal, 'r', 'LineWidth', 1.5);
title('Ambulance Transmitter (Tx)');
xlabel('Time (s)');
ylabel('Signal');
grid on;
ylim([-1.5 1.5]);

% Receiver signal
subplot(4,1,2);

plot(t, Rx_signal, 'b', 'LineWidth', 1.5);
title('Vehicle Receiver (Rx) - Delayed Signal');
xlabel('Time (s)');
ylabel('Signal');
grid on;
ylim([-1.5 1.5]);

% Cyron alert
subplot(4,1,3);

plot(t, Cyron_alert, 'g', 'LineWidth', 1.5);
title('In-Car Cyron Alert Activation');
xlabel('Time (s)');
ylabel('Alert');
grid on;
ylim([-0.5 1.5]);

% Driver response
subplot(4,1,4);

plot(t, Driver_Response, 'm', 'LineWidth', 1.5);
title('Driver Response');
xlabel('Time (s)');
ylabel('Response');
grid on;
ylim([-0.5 2.5]);

%% 8. SIMULATION COMPLETION MESSAGE

disp('---------------------------------------------');
disp(' Smart Traffic System Simulation Completed');
disp('---------------------------------------------');
disp(['Communication Delay: ', num2str(delay), ' seconds']);
disp(['Proportional Gain Kp: ', num2str(Kp)]);
disp('Emergency signal successfully transmitted.');
disp('Vehicle receiver successfully detected the signal.');
disp('Cyron alert activated.');
disp('Driver response generated.');
